var { findWords, findAllWords, compareStr } = require("./tool");

var test = compareStr("hello", 3, "load", 0, 2);
console.log(test);

var article = `I immediately went to work with this piece of ground; and in less than a month’s time I had so fenced it round that my flock, or herd, call it which you please, which were not so wild now as at first they might be supposed to be, were well enough secured in it: so, without any further delay, I removed ten young she-goats and two he-goats to this piece, and when they were there I continued to perfect the fence till I had made it as secure as the other; which, however, I did at more leisure, and it took me up more time by a great deal. All this labour I was at the expense of, purely from my apprehensions on account of the print of a man’s foot; for as yet I had never seen any human creature come near the island; and I had now lived two years under this uneasiness, which, indeed, made my life much less comfortable than it was before, as may be well imagined by any who know what it is to live in the constant snare of the fear of man. And this I must observe, with grief, too, that the discomposure of my mind had great impression also upon the religious part of my thoughts; for the dread and terror of falling into the hands of savages and cannibals lay so upon my spirits, that I seldom found myself in a due temper for application to my Maker; at least, not with the sedate calmness and resignation of soul which I was wont to do: I rather prayed to God as under great affliction and pressure of mind, surrounded with danger, and in expectation every night of being murdered and devoured before morning; and I must testify, from my experience, that a temper of peace, thankfulness, love, and affection, is much the more proper frame for prayer than that of terror and discomposure: and that under the dread of mischief impending, a man is no more fit for a comforting performance of the duty of praying to God than he is for a repentance on a sick-bed; for these discomposures affect the mind, as the others do the body; and the discomposure of the mind must necessarily be as great a disability as that of the body, and much greater; praying to God being properly an act of the mind, not of the body.`;

var result = findWords(article, "to", 0);
console.log(result)
var arr = findAllWords(article, "to");
console.log(arr);
